name: echo pr title
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
