name: echo pr title
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}
